# Generated by Django 4.2 on 2025-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rate from 1 (worst) to 5 (best)'),
        ),
    ]
